export const QUESTIONS_LOADED = "QUESTIONS_LOADED";
export const QUESTIONS_LOADED_FAIL = "QUESTIONS_LOADED_FAIL";

export const SET_CURRENT = "SET_CURRENT";
export const RESET_STATE = "RESET_STATE";

export const SET_ANSWERS = "SET_ANSWERS";
export const CORRECT_ANSWER = "CORRECT_ANSWER";
export const INCORRECT_ANSWER = "INCORRECT_ANSWER";
export const UPDATE_BANK = "UPDATE_BANK";

export const GAME_OVER = "GAME_OVER";
export const GET_USERS = "GET_USERS";

export const SET_USERNAME = "SET_USERNAME";
